app.js

subject : app.js 파일에 router 파일 export 하는 부분 누락되서 추가했습니다

FEAT : :sparkles: app.js 라우터 export 추가

---

.babelrc
.eslintignore
.sequelizerc
config/config.js
exportDataToExcel.js
migrations/20230304194425-create-user.js
migrations/20230304195122-create-utm.js
migrations/20230304195310-create-user-utm-medium.js
migrations/20230304195329-create-user-utm-source.js
migrations/20230304195523-create-user-utm.js
models/index.js
models/user.js
models/user_utm.js
models/user_utm_medium.js
models/user_utm_source.js
models/utm.js
package-lock.json
package.json
src/config/dbconfig.js

기존 방식에서 passport.js 를 이용해서 구현.
로컬 테스트는 확인했는데 PR merge 되면 배포되있는 서버에서 다시 테스트 예정
```javascript
router.get('/auth/kakao', authPassport);
router.get('/auth/kakao/callback', authPassport, (req, res, next) => {
console.log(process.env.CLIENT_URL);
res.redirect('/');
});
```

💩 sequelize db:migrate 중 babel version error 상태 

---

app.js
src/routes/userRouter.js
src/routes/utmRouter.js

* 환경변수에 맞게 세팅했습니다. 로컬에서 테스트할 때랑 배포 후 실행할 때 환경으로 세팅했습니다.

:recycle: http & https 배포 환경에 맞게 설정, api 에 authentication 미들웨어 추가

---

app.js
migrations/20230315021521-users.cjs
models/users.js
src/controllers/utm/utm-crud.js
src/modules/user.module.js
utils/middleware.js

* ssl 인증서 접근 권한 이슈로 인해서 기존의 http 로 서버를 열고 nginx 를 사용해서 reverse_proxy 로 연결했습니다.
* autoincrease 로 다시 변경했습니다. 카카오에서 주는 id 가 일정하지 않습니다.

:recycle: 서버 테스트 후 불필요한 코드 제거 및 유저 디비 수정

---

app.js
src/routes/userRouter.js
utils/middleware.js

* origin 을 프론트 도메인으로 설정하고 credential 을 true 로 열었습니다.

:recycle: header 설정

---

app.js
migrations/20230315021521-users.cjs
package-lock.json
package.json
src/config/kakaoStrategy.js
src/modules/user.module.js
src/routes/userRouter.js
utils/middleware.js

* auto-increase 설정이랑, 초기값까지 설정.
* 기초 보안 설정

♻️  autoIncreament 다시 설정 & cookie 전달. & helmet 설정

---

src/controllers/utm/utm-crud.js
src/modules/utm.module.js
src/routes/userRouter.js
utils/middleware.js

* utm이 여러개가 넘어와서 각 요소마다 작업하도록 설정.

♻️ createUtm 배열로 받아서 생성.

---

src/controllers/utm/utm-crud.js
src/modules/utm.module.js

* map 이 돌면서 에러가 발생해도 처리해주지 않아서 map 이 다 돌때까지 대기 후 결과에서 에러를 검토하고 response 하도록 수정.

♻️ createUTM 부분 에러처리 수정

---

utils/middleware.js

♻️ email 제공 안하고 회원가입 시도 시 login 페이지로 redirect

---

src/modules/utm.module.js

:recycle: 외부 UTM 추가할 때 날짜 입력값으로 데이터 생성하기.

---

app.js
migrations/20230315021142-utms.cjs
src/controllers/utm/utm-crud.js
src/controllers/utm/utmMemo.js
src/modules/utm.module.js
src/routes/utmRouter.js

```javascript
// created_at 입력받은 값이 있으면 그걸로 반영 , 없으면 현재 날짜로 'YYYY-MM-DD' 로 변환
const dateOnly = new Date(created_at || Date.now()).toISOString().slice(0, 10);
```
* 성현님 테스트 완
* 성현님 테스트 완

♻️  created_at 'YYYY-MM-DD' 로 변환 & 삭제 로직 변경 & 메모 수정 성현님 PR 반영

---

src/modules/utm.module.js

:hammer:  umt.module.js 추가

---

package-lock.json
package.json
src/controllers/utm/utm-crud.js
src/modules/utm.module.js
src/routes/userRouter.js

* 디비에 넣을 때 설정을 해주어도 자동으로 시간이 들어가버리면서 가져올 때 또 시간이 나옴
* 아예 뺄 때도 거르도록 수정

:bug: 전체 데이터 날짜 수정 & 엔드포인트 수정

---

src/config/dbconfig.js

메모 수정하기 API 와 연결된 DB 커넥션 부분이 오류가 있어서 작동 오류가 있었습니다.
올바른 DB 커넥션으로  변경하였습니다.

FIX : DB 커넥션 부분 오류 변경

---

migrations/20230315021142-utms.cjs
models/utms.js
src/controllers/utm/utm-crud.js

:bug: 전체 UTM return 수정

---

src/controllers/utm/utm-crud.js
src/modules/utm.module.js

🐛 shorten url throw 주석

---

app.js

* 허용할 도메인을 배열에 넣은 후 맞는 도메인일 때 true 로 허용

🚀 프론트 로컬 테스트환경 cors origin 동적 할당

---

src/modules/utm.module.js

:recycle: 빈 값에 null 대신 '-' 입력

---

.github/workflows/deploy.yml

* deploy.yml 파일 추가
* 레포 secret 에 환경변수 설정

👷 CD 를 위한 yml 파일 추가

---

src/controllers/utm/exportDataToCsv.js

* 기존에 있던 로직이 기능적으로 불안하여 작동이 안되던 부분들을 수정하였습니다.
* SQL 쿼리문을 이전보다 효율적으로 개선하기 위해 JOIN 문을 추가하였으며, PM 분들의 요구사항에 따라서 테이블에 담기는 헤더값을 수정하였습니다. 
* 파일의 경로 문제와 formatter 문제로 생성이 안되거나 읽기가 되지 않아서 추출하기가 되지 않던 부분을 수정하였습니다.
<br>

REFACTOR : :recycle: CSV 파일 추출하기 로직 코드개선 및 안정성 확보

---

package-lock.json
package.json
src/modules/utm.module.js

⚡ shortener 다른 서비스 교체

---

src/controllers/utm/exportDataToCsv.js
src/routes/utmRouter.js

TEST : 로컬환경에서 테스트하는 환경을 그대로 적용해서 요청 메소드를 POST 가 아닌 GET 요청으로 변경해보고 다운로드가 되는지 테스트

FIX : 파일 추출하기 메소드를 GET 요청으로 변경

---

src/controllers/utm/utm-crud.js
src/modules/utm.module.js

♻️ fix make shorten url

---

src/controllers/user/companySignup.js

⚡ nodemailer 양식 추가

---

src/controllers/utm/utmMediumTags.js
src/controllers/utm/utmSourceTags.js
src/routes/utmRouter.js

1. 유티엠의 소스 태그기능을 위한 조회 api 구현하였습니다.
2. 유티엠의 미디움 태그 기능을 위한 조회 api 구현하였습니다.
---
* 초기 mvp 내용중 하나인 태그 기능을 위한 API 구현하였으나 프론트의 테이블 이슈로 당장의 추가적인 진행은 없을듯 합니다.
* 프론트에서도 구현할 수 있는 형태로 바뀔수도 있는 코드들이며 추후 변경사항 발생시 다시 리팩토링 하도록 하겠습니다.

FEAT : :sparkles: UTM 소스, 미디움 태그 추가

---

src/controllers/utm/utm-crud.js
src/routes/utmRouter.js

* 회원가입하지 않고 UTM 생성하기를 체험하기 위한  API 추가하였습니다.
* 기존 로직에서 아이디 부분만 수정하여 새로운 API 로 다시 만들었습니다.
* 추후 이 아이디로 만들어진 UTM 들 자동 삭제하는 로직도 추가하도록 하겠습니다.

FEAT : 	:sparkles: 유저 체험용 생성하기 api 추가

---

.gitignore
app.js
config/config.js
migrations/20230329143911-logintype.cjs
src/controllers/user/companySignup.js
src/routes/userRouter.js

♻️ nodemailer 에서 email 검증 추가

---

package.json
src/routes/userRouter.js

FIX : :wrench: 구글 로그인 위한 패키지 누락으로 인한 추가 및 병합충돌 해결

---

src/passport/googleStrategy.js

FIX : :memo: 로그인시 로그인 타입 추가

---

package.json
src/passport/googleStrategy.js
src/routes/userRouter.js

구글 로그인을 위한 패키지가 깃허브액션의 현재 버전에서 사용이 불가능하여 
깃허브액션 조치 후 다시 파일추가 하겠습니다.

Fixes: :ambulance: 구글로그인 패키지버전으로 인한 깃허브액션 미작동 긴급조치

---

.github/workflows/deploy.yml

Fixes: : 구글로그인 실행을 위한 CD 파일 변경

---

package.json
src/controllers/utm/exportDataToCsv.js
src/passport/googleStrategy.js
src/routes/userRouter.js
src/routes/utmRouter.js

FIX : 구글로그인 재시도

---

package-lock.json

FEAT : package-lock 추가

---

src/controllers/user/companySignup.js
src/modules/jwt.module.js
src/modules/user.module.js
src/routes/userRouter.js
utils/middleware.js

:recycle: 로그인 방식 통합(토큰 통합)

---

src/routes/utmRouter.js

FIX : 추출하기 엔드포인트 변경

---

src/controllers/utm/exportDataToCsv.js

FIX : 추출하기 파일 네임 변경

---

src/controllers/utm/exportDataToCsv.js

FIX : 데이터 추출하기 Content-Disposition 변경

FIX : 데이터 추출하기 Content-Disposition 변경

---

export/UTM_Data_File_CSV.csv

FIX : 추출하기 폴더 위치 추가

---

src/controllers/utm/exportDataToCsv.js
src/routes/utmRouter.js

FIX : get 요청으로 변경한 후 url test

---

src/controllers/utm/exportDataToCsv.js
src/routes/utmRouter.js

FIX : 추출하기 url 값 post 요청으로 변경

---

src/routes/userRouter.js

* 메소드 변경
* request url 변경
* request 요청값 변경
* 반복문 변경하여 await 기능 확정

REFACTOR : 회원탈퇴 메소드 변경 및 반복문 변경, req 값 변경

---

src/controllers/user/userWithdrawal.js
src/modules/mongo.module.js
src/routes/userRouter.js

:ambulance: 회원탈퇴 로직 수정

---

src/controllers/utm/exportDataToExcel.js

REFACTOR : UTM 엑셀파일로 추출하기 코드 개선

---

src/controllers/utm/exportDataToCsv.js

FIX : csv 파일로 추출하기 동기식으로 코드 변경

FIX : csv 파일로 추출하기 동기식으로 코드 변경

---

src/controllers/utm/exportDataToCsv.js

FIX : 추출하기 파일 기존파일로 변경

---

src/controllers/utm/exportDataToCsv.js

REFACTOR : :white_check_mark: csv 파일 추출하기 팬딩과정 변경

REFACTOR : :white_check_mark: csv 파일 추출하기 팬딩과정 변경

---

src/passport/googleStrategy.js
src/routes/userRouter.js
utils/middleware.js

* 로그인 시 리턴값으로 엑세스 토큰 및 리프레시 토큰 추가
* 로그인시 인증 middleware 에 로그인 타입에 따른 인증 로직 추가
* 미들웨어 로직 확인 후 프론트엔드와 연결 테스트 진행예정
UWR-20

REFACTOR : :recycle: 구글 로그인 인증방식 변경 및 코드 수정

---

src/controllers/utm/importDataToExcel.js

FIX ::wrench: 연석님 파일 롤백 테스트

---

src/controllers/utm/exportDataToCsv.js

:wrench: FIX : 대용량 업로드 양식을 위해 key값으로 사용될 값으로 쿼리수정

:wrench: FIX : 대용량 업로드 양식을 위해 key값으로 사용될 값으로 쿼리수정
